'use client';

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import { SessionProvider } from 'next-auth/react'
import Navbar from '@/components/Navbar'
import ToastProvider from '@/components/ToastProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <Navbar />
          <ToastProvider />
          {children}
          <Script 
            type="text/javascript"
            src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=99f2b83b3b9cd67eddfe991431963ff0&libraries=services,clusterer&autoload=false`}
          />
        </SessionProvider>
      </body>
    </html>
  )
}
